### ISSUE TITLE
Grid-spacing and optimized-values

### ISSUE THREAD

**Issue by DRL** [DRL/gIMble#18]
- global optima should be saved in ZARR store.
  - we can't save optima in INI file since it would not work with unique_hash of INI (we could not determine identity)
- so how to deal with center of grid?
- M_e should be treated differently than other params?

**Comment by KLohse** [comment]
On 2nd thought specifying grid points via the ini file should be simplified. Trying to centre grids on the para point found by optimize introduces more problems than it solve because we have to link the output of optimize to the input of makegrid which is fiddly (lots of checks would be required).
 
- the centre of the grid matters only in terms of the best fitting global model (all paras are the same across windows) not in the sense of the actual centre. It should be possible to set up grids where the best point is choosen not to be in the centre, i.e. for m_e which has a leptokurtic distribution
- optimize and gridsearch are usually run on different data (blocks vs windows) anyway and there is no way around this difference, so the optimise MCLE para point is not excactly the same as the best global point windowwise data. 
- we want to be able to use gridsearch even without having fitted a global model beforehand
 
So my suggested solution is:

- get rid of the centre entirely, i.e. specifying (min, max, #gridpoints) for all parameters in makegrid should be enough. 
- #gridpoints includes min and max, so (min, max, 2) makes a grid conisting only of min and max 
- when running gridsearch on windowise data we determine the best fitting global gridpoint from the data as a first step and report this parameter point and the associated lnCL on screen to the user
- this best global gridpoint is assumed to be the 'centre' for the purpose of computing differences in lnCL for each window.

**Comment by DRL** [comment]
> On 2nd thought specifying grid points via the ini file should be simplified. Trying to centre grids on the para point found by optimize introduces more problems than it solve because we have to link the output of optimize to the input of makegrid which is fiddly (lots of checks would be required).
>
> - the centre of the grid matters only in terms of the best fitting global model (all paras are the same across windows) not in the sense of the actual centre. It should be possible to set up grids where the best point is choosen not to be in the centre, i.e. for m_e which has a leptokurtic distribution
> - optimize and gridsearch are usually run on different data (blocks vs windows) anyway and there is no way around this difference, so the optimise MCLE para point is not excactly the same as the best global point windowwise data.
> - we want to be able to use gridsearch even without having fitted a global model beforehand
   
I agree.

> So my suggested solution is:

> - get rid of the centre entirely, i.e. specifying (min, max, #gridpoints) for all parameters in makegrid should be enough.
> - #gridpoints includes min and max, so (min, max, 2) makes a grid conisting only of min and max
> - when running gridsearch on windowise data we determine the best fitting global gridpoint from the data as a first step and report this parameter point and the associated lnCL on screen to the user
> - this best global gridpoint is assumed to be the 'centre' for the purpose of computing differences in lnCL for each window.

Agree. But...

- INI format should be `(min, [max, [#gridpoints, distribution]])` so that 
  - `min` can be used for single point `gridsearch` runs
  - `min, max` can be used in `optimise`
  - `min, max, #gridpoints, distribution` can be used in `makegrid`, `gridsearch`

- should we rename `gridsearch` into `search`?

- regarding the last point, you are saying to run the grid against one single bSFS, composed of the sum of all window-bSFSs (point c) below), and declare the best scoring gridpoint to be the center, right? 

- can we agree on a terminology for bSFSs?
  a) bSFS : block-wise SFS (4D)
  b) wbSFS : window-wise bSFS (5D)   
  c) and then we would need a name for SUM(wbSFS) -> bSFS

**Comment by DRL** [comment]
- [ ] Change parameter parsing of INI (@GertjanBisschop)
- [ ] build function to get sum-wbSFS from gimbleStore (@DRL)

**Comment by DRL** [comment]
Coding is finished, still have to check that numbers make sense based on real data

**Comment by DRL** [comment]
Added more functionality to `query`, now supports :
- 2D bsfs out put of bSFS and sum-wbSFS 
- more verbose BED output
- BED output for wbSFS now includes popgen_metrics 

hope things work...
