### ISSUE TITLE
Make optimise work on parametric bootstrap sims for a global model

### ISSUE THREAD

**Issue by KLohse** [DRL/gIMble#8]
A very common workflow (i.e. all published analyses using the mathemtaica implementation) for working out CI of estimates under the global model is:

- [x] generate replicate (100-500 usually do the trick) simulated datasets (aka pseuodobserved datasets PODS) with recommination under some inferred global model. Each sim dataset is generally of the same size as the real data (and possibly split up into idealized chroms to make the simulating  #feasible)
- [x] summarise each rep by one global bSFS
- [x] fit the global model to each rep using optimise
- [x] find the SD in parameter estimates across reps (assuming MCLE are normally distributed 2SD is an estimate of 95%CI). Alternatively (for paras near the bound e.g. low M estimates as in Noora's case), one may want to inspect the 2.5% and 97.5% quantile of the distribution of para estimates.

It should be possible to implement this by optimise in batch mode. The output would be a .tsv file with the best fittting MCLE for each rep (row). 
Stuff to think about: 
- maximise parallelisation! 
- Ideally this should behave in the same way as running optimise on windows
- Should it be possible to run replicate searches for each sim (I havn't done this ever) and how would we record this in the .tsv? 
- The summarising of the .tsv info could be done with a post processing script. This would force users to look at and think about the distribution of para estimates (do they look normal? how confounded are para estimates etc?)
- This should also work for sims generate under the wrong model (para bootstraps to compare the power to distinguish between models).

**Comment by GertjanBisschop** [comment]
>     * Should it be possible to run replicate searches for each sim (I havn't done this ever) and how would we record this in the .tsv?

But also, do we want to start optimisation for each global bsfs to start at the same point or at random points (intuitively I would say random).
And, when you say replicate searches, do you mean starting at different starting points?

**Comment by GertjanBisschop** [comment]
After our discussion: optimisation for single replicates will always start from the same point = midpoint for all boundaries. This to ensure we are not testing for variance because of the simulations and not because of specifying different starting points (although given our likelihood surface is well-behaved in general, this should not matter). Secondly, this also ensures that proper specification of the boundaries can result in significant speed-ups of the optimisation routine.

Given that we assume (but will be checked) that the optimum found is a global optimum, there is no need for the optimisation to have multiple independent starting points.

**Comment by GertjanBisschop** [comment]
Resolved in commits b5563ae 8da829e4a6935f0745c65d97b43a4a9576573bba.
